Expose vector retrieval by key in Swift & Objective-C libraries
unum-cloud/usearch pull request #455
Opened 2024-08-03 04:48 UTC by brittlewis12

Thank you for the fantastic library, @ashvardanian! I'm using it quite happily for a couple different projects, and I'm excited for the opportunity to contribute back in a small way.

### This PR adds two new features to the Swift & Obj-C libraries:

1. vector retrieval by key (`get`)
1. constructing indexes with `multi`-vector keys enabled

& add tests to exercise the new `get` interfaces & `multi` configuration on the swift side.

### a couple notes:
* for the multi case:
    - the obj-c side doesn't do any work to break up the single large vector if a count greater than one is returned. this mirrors the cpp seam.
    - the swift seam returns a 2d array instead.
* there's a bit of duplication in the `get` implementations, both on the objective-c and on the swift side
* the swift 'sugar' interfaces are a bit less than ergonomic than they could be, requiring explicit typing on the expected return value at the callsite, since the parameters alone aren't enough to disambiguate. didn't think it was worth going further without feedback

---

<details><summary>tests are passing locally:</summary>

```
❯ swift build && swift test -v
Building for debugging...
[2/2] Emitting module USearch
Build complete! (0.87s)
Planning build
Building for debugging...
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -module-name USearch -incremental -emit-dependencies -emit-module -emit-module-path /Users/tito/code/usearch/.build/arm64-apple-macosx/debug/USearch.swiftmodule -output-file-map /Users/tito/code/usearch/.build/arm64-apple-macosx/debug/USearch.build/output-file-map.json -parse-as-library -c /Users/tito/code/usearch/swift/Index+Sugar.swift /Users/tito/code/usearch/swift/USearch.swift -I /Users/tito/code/usearch/.build/arm64-apple-macosx/debug -target arm64-apple-macosx10.13 -swift-version 5 -v -enable-batch-mode -index-store-path /Users/tito/code/usearch/.build/arm64-apple-macosx/debug/index/store -Onone -enable-testing -g -j10 -DSWIFT_PACKAGE -DDEBUG -Xcc -fmodule-map-file=/Users/tito/code/usearch/.build/arm64-apple-macosx/debug/USearchObjective.build/module.modulemap -Xcc -I -Xcc /Users/tito/code/usearch/objc/include -module-cache-path /Users/tito/code/usearch/.build/arm64-apple-macosx/debug/ModuleCache -parseable-output -parse-as-library -emit-objc-header -emit-objc-header-path /Users/tito/code/usearch/.build/arm64-apple-macosx/debug/USearch.build/USearch-Swift.h -color-diagnostics -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -L /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -Xcc -isysroot -Xcc /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -Xcc -F -Xcc /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -Xcc -fPIC
Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx10.13
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -module-name USearchTests -incremental -emit-dependencies -emit-module -emit-module-path /Users/tito/code/usearch/.build/arm64-apple-macosx/debug/USearchTests.swiftmodule -output-file-map /Users/tito/code/usearch/.build/arm64-apple-macosx/debug/USearchTests.build/output-file-map.json -parse-as-library -c /Users/tito/code/usearch/swift/Test.swift -I /Users/tito/code/usearch/.build/arm64-apple-macosx/debug -target arm64-apple-macosx13.0 -swift-version 5 -v -enable-batch-mode -index-store-path /Users/tito/code/usearch/.build/arm64-apple-macosx/debug/index/store -Onone -enable-testing -g -j10 -DSWIFT_PACKAGE -DDEBUG -Xcc -fmodule-map-file=/Users/tito/code/usearch/.build/arm64-apple-macosx/debug/USearchObjective.build/module.modulemap -Xcc -I -Xcc /Users/tito/code/usearch/objc/include -module-cache-path /Users/tito/code/usearch/.build/arm64-apple-macosx/debug/ModuleCache -parseable-output -parse-as-library -color-diagnostics -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -L /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -Xcc -isysroot -Xcc /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -Xcc -F -Xcc /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -Xcc -fPIC
Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx13.0
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file /Users/tito/code/usearch/swift/Test.swift -emit-dependencies-path /Users/tito/code/usearch/.build/arm64-apple-macosx/debug/USearchTests.build/Test.d -emit-reference-dependencies-path /Users/tito/code/usearch/.build/arm64-apple-macosx/debug/USearchTests.build/Test.swiftdeps -target arm64-apple-macosx13.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -stack-check -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -I /Users/tito/code/usearch/.build/arm64-apple-macosx/debug -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -color-diagnostics -enable-testing -g -module-cache-path /Users/tito/code/usearch/.build/arm64-apple-macosx/debug/ModuleCache -swift-version 5 -Onone -D SWIFT_PACKAGE -D DEBUG -new-driver-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-driver -empty-abi-descriptor -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -Xcc -fmodule-map-file=/Users/tito/code/usearch/.build/arm64-apple-macosx/debug/USearchObjective.build/module.modulemap -Xcc -I -Xcc /Users/tito/code/usearch/objc/include -Xcc -isysroot -Xcc /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -Xcc -F -Xcc /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -Xcc -fPIC -module-name USearchTests -disable-clang-spi -target-sdk-version 14.2 -target-sdk-name macosx14.2 -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/local/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -plugin-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain [...]

2024-08-19 19:53 UTC, ashvardanian requested changes

2024-08-19 19:53 UTC, ashvardanian commented on objc/USearchObjective.mm
> +    }
We probably don't need this check.

2024-08-19 19:53 UTC, ashvardanian commented on objc/USearchObjective.mm
> +    }
We probably don't need this check.

2024-08-21 19:59 UTC, merged

2024-08-21 19:59 UTC, ashvardanian commented
Thanks for a great quality contribution @brittlewis12 🤗

2024-08-21 20:50 UTC, brittlewis12 commented on objc/USearchObjective.mm
> +    }
thank you! 🙏